branch-defaults:
  master:
    environment: submit-prod
environment-defaults:
  submit-prod:
    branch: null
    repository: null
global:
  application_name: submit
  default_platform: Java 8
  default_ec2_keyname: javabin
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running Java 8
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip
